apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: healthops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:13.0.1
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: healthops-secrets
                  key: GRAFANA_ADMIN_USER
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: healthops-secrets
                  key: GRAFANA_ADMIN_PASSWORD
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
              subPath: datasources.yaml
            - name: grafana-dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards/dashboard-provider.yaml
              subPath: dashboard-provider.yaml
            - name: grafana-dashboard
              mountPath: /var/lib/grafana/dashboards/healthops-dashboard.json
              subPath: healthops-dashboard.json
      volumes:
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
        - name: grafana-dashboard-provider
          configMap:
            name: grafana-dashboard-provider
        - name: grafana-dashboard
          configMap:
            name: grafana-healthops-dashboard
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: healthops
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
